//
// Created by han8293 on 2/24/2017.
//

#ifndef LIDARVISUALIZER_MESSAGE_H
#define LIDARVISUALIZER_MESSAGE_H

enum LAS_ERROR {
  LAS_OK,
    LAS_FAIL,
    LAS_EMPTY_FILENAME,
    LAS_FILE_NOT_EXIST
};

#endif //LIDARVISUALIZER_MESSAGE_H
