//
// Created by han8293 on 2/24/2017.
//

#ifndef LIDARVISUALIZER_MESSAGE_H
#define LIDARVISUALIZER_MESSAGE_H

enum LAS_ERROR {
  LAS_OK,
    LAS_INVALID_FILENAME,
    LAS_INVALID_POINT_DATA_FORMAT
};

#endif //LIDARVISUALIZER_MESSAGE_H
